# Generated by Django 4.0.4 on 2022-05-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hi',
            field=models.TextField(blank=True),
        ),
    ]
