# Generated by Django 4.0.4 on 2022-05-29 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_user_hi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hi',
        ),
    ]
