# Generated by Django 4.0.4 on 2022-05-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_user_blogmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='username',
        ),
    ]
