# Generated by Django 4.0.4 on 2022-05-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='author',
        ),
    ]
