# Generated by Django 4.0.4 on 2022-05-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
