# Generated by Django 4.0.4 on 2022-05-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='author',
        ),
    ]
