# Generated by Django 4.0.4 on 2022-06-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogmodel_is_like_blogmodel_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='LikeModel',
        ),
    ]
