# Generated by Django 4.0.4 on 2022-06-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_commentmodel_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='active',
            new_name='activate',
        ),
    ]
