# Generated by Django 4.0.4 on 2022-06-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_commentmodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
